// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneBigHead.Server.Data;

#nullable disable

namespace OneBigHead.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OneBigHead.Server.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("categoryId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("visibility");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.CategoryItemTemplate", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("CategoryId", "ItemTemplateId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ItemTemplateId");

                    b.ToTable("CategoryItemTemplates");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("collectionId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("HeroImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("visibility");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("WorkspaceId", "Slug")
                        .IsUnique();

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.CollectionItemHighlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("CollectionId", "ItemId")
                        .IsUnique();

                    b.HasIndex("CollectionId", "ViewCount");

                    b.ToTable("CollectionItemHighlights");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.CollectionItemTemplate", b =>
                {
                    b.Property<int>("CollectionId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("CollectionId", "ItemTemplateId");

                    b.HasIndex("ItemTemplateId");

                    b.ToTable("CollectionItemTemplates");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.CollectionStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer");

                    b.Property<int>("StatisticType")
                        .HasColumnType("integer");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("CollectionId", "StatisticType")
                        .IsUnique();

                    b.ToTable("CollectionStatistics");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.CollectionTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("CollectionThemes");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.CollectionThemeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParentName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("ThemeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId");

                    b.ToTable("CollectionThemeCategories");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.CollectionThemeTemplate", b =>
                {
                    b.Property<int>("ThemeId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("ThemeId", "ItemTemplateId");

                    b.HasIndex("ItemTemplateId");

                    b.HasIndex("ThemeId");

                    b.ToTable("CollectionThemeTemplates");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.ContentScanLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageHash")
                        .HasColumnType("text");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("boolean");

                    b.Property<double>("MatchScore")
                        .HasColumnType("double precision");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text");

                    b.Property<bool>("ReportSubmitted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScannerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsMatch");

                    b.HasIndex("ScannedAt");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("ContentScanLogs");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("categoryId");

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("collectionId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("description");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("images");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("properties");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasJsonPropertyName("summary");

                    b.Property<Guid?>("TemplateKey")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("templateKey");

                    b.Property<int>("UserFlag")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("userFlag");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("visibility");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("workspaceId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CollectionId");

                    b.HasIndex("UserFlag");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("CollectionId", "CreatedAt");

                    b.HasIndex("WorkspaceId", "TemplateKey");

                    b.HasIndex("WorkspaceId", "UserFlag");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.ItemTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("itemTemplateId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TemplateKey")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WorkspaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("ItemTemplates");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.ItemTemplateProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("itemTemplatePropertyId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ItemTemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemTemplateId");

                    b.ToTable("ItemTemplateProperties");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.PropertySuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("CollectionId", "Type");

                    b.HasIndex("CollectionId", "Type", "Value")
                        .IsUnique();

                    b.ToTable("PropertySuggestions");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.StoredImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("StoredImages");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.SupportReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("supportReplyId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFromAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("SupportRequestId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SupportRequestId");

                    b.HasIndex("UserId");

                    b.HasIndex("SupportRequestId", "IsFromAdmin", "IsRead");

                    b.ToTable("SupportReplies");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.SupportRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("supportRequestId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("SupportRequests");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedTermsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ActiveWorkspaceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("IdentityProvider")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemAdministrator")
                        .HasColumnType("boolean");

                    b.Property<string>("ProviderSubjectId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveWorkspaceId");

                    b.HasIndex("Email");

                    b.HasIndex("IdentityProvider", "ProviderSubjectId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasCompletedWelcome")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("\"Slug\" IS NOT NULL");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.WorkspaceStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("StatisticType")
                        .HasColumnType("integer");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("WorkspaceId", "StatisticType", "Date")
                        .IsUnique();

                    b.ToTable("WorkspaceStatistics");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.WorkspaceUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkspaceRole")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "WorkspaceId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WorkspaceUsers");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.Category", b =>
                {
                    b.HasOne("OneBigHead.Server.Models.Collection", "Collection")
                        .WithMany("Categories")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneBigHead.Server.Models.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OneBigHead.Server.Models.Workspace", "Workspace")
                        .WithMany("Categories")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("ParentCategory");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.CategoryItemTemplate", b =>
                {
                    b.HasOne("OneBigHead.Server.Models.Category", "Category")
                        .WithMany("CategoryItemTemplates")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneBigHead.Server.Models.ItemTemplate", "ItemTemplate")
                        .WithMany("CategoryItemTemplates")
                        .HasForeignKey("ItemTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ItemTemplate");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.Collection", b =>
                {
                    b.HasOne("OneBigHead.Server.Models.Workspace", "Workspace")
                        .WithMany("Collections")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.CollectionItemHighlight", b =>
                {
                    b.HasOne("OneBigHead.Server.Models.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneBigHead.Server.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.CollectionItemTemplate", b =>
                {
                    b.HasOne("OneBigHead.Server.Models.Collection", "Collection")
                        .WithMany("CollectionItemTemplates")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneBigHead.Server.Models.ItemTemplate", "ItemTemplate")
                        .WithMany("CollectionItemTemplates")
                        .HasForeignKey("ItemTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("ItemTemplate");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.CollectionStatistic", b =>
                {
                    b.HasOne("OneBigHead.Server.Models.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneBigHead.Server.Models.CollectionThemeCategory", b =>
                {
                    b.HasOne("OneBigHead.Server.Models.CollectionTheme", "Theme")
                        .WithMany("ThemeCategories")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.CollectionThemeTemplate", b =>
                {
                    b.HasOne("OneBigHead.Server.Models.ItemTemplate", "ItemTemplate")
                        .WithMany()
                        .HasForeignKey("ItemTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneBigHead.Server.Models.CollectionTheme", "Theme")
                        .WithMany("ThemeTemplates")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemTemplate");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.Item", b =>
                {
                    b.HasOne("OneBigHead.Server.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OneBigHead.Server.Models.Collection", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneBigHead.Server.Models.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Collection");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.ItemTemplate", b =>
                {
                    b.HasOne("OneBigHead.Server.Models.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.ItemTemplateProperty", b =>
                {
                    b.HasOne("OneBigHead.Server.Models.ItemTemplate", "ItemTemplate")
                        .WithMany("Properties")
                        .HasForeignKey("ItemTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemTemplate");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.PropertySuggestion", b =>
                {
                    b.HasOne("OneBigHead.Server.Models.Collection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneBigHead.Server.Models.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.StoredImage", b =>
                {
                    b.HasOne("OneBigHead.Server.Models.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.SupportReply", b =>
                {
                    b.HasOne("OneBigHead.Server.Models.SupportRequest", "SupportRequest")
                        .WithMany("Replies")
                        .HasForeignKey("SupportRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneBigHead.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SupportRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.SupportRequest", b =>
                {
                    b.HasOne("OneBigHead.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.User", b =>
                {
                    b.HasOne("OneBigHead.Server.Models.Workspace", "ActiveWorkspace")
                        .WithMany("ActiveUsers")
                        .HasForeignKey("ActiveWorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActiveWorkspace");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.WorkspaceUser", b =>
                {
                    b.HasOne("OneBigHead.Server.Models.User", "User")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneBigHead.Server.Models.Workspace", "Workspace")
                        .WithMany("WorkspaceUsers")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.Category", b =>
                {
                    b.Navigation("CategoryItemTemplates");

                    b.Navigation("ChildCategories");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.Collection", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("CollectionItemTemplates");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.CollectionTheme", b =>
                {
                    b.Navigation("ThemeCategories");

                    b.Navigation("ThemeTemplates");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.ItemTemplate", b =>
                {
                    b.Navigation("CategoryItemTemplates");

                    b.Navigation("CollectionItemTemplates");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.SupportRequest", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.User", b =>
                {
                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("OneBigHead.Server.Models.Workspace", b =>
                {
                    b.Navigation("ActiveUsers");

                    b.Navigation("Categories");

                    b.Navigation("Collections");

                    b.Navigation("WorkspaceUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
